{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#importing all libraries and packages\n",
    "import pandas as pd\n",
    "from googlemaps import Client as GoogleMaps\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/morganbernstein/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (55,61,66,67,69,70,71,72,75,77) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "/Users/morganbernstein/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (55,60,61,63,64,65,66,67,69,70,71,72,75,77,138,139,141,142,143,144,145,147,148,149,150,151,153,154,155,156,157,159,160,161,162,163,165,166,167,168,169,171,172,173,174,175,177,178,179,180,181,183,184,185,186,187,189,190,191,192,193,195,196,197,198,199,201,202,203,204,205,207,208,209,210,211,213,214,215,216,217,219,220,221,222,223,225,226,227,228,229,231,232,233) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n"
     ]
    }
   ],
   "source": [
    "#reading in csv file **this csv is an old one of ours that is now in the archives folder, it does not have coordinates\n",
    "arrests = pd.read_csv(\"/Users/morganbernstein/Desktop/DATA+/SToPAGetDurhamData/10 Clean Data/clean02.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#loading in google maps api key\n",
    "gmaps = GoogleMaps(\"AIzaSyBrCWi4m0TZRZ8ntHAJ8maVbgIw0gsv4Bg\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "#creating new longitude and latitude columns in the dataframe that don't have any values yet\n",
    "arrests[\"longitude\"] = \"\"\n",
    "arrests[\"latitude\"] = \"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-14-3e04e6a4b050>:6: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  arrests[\"latitude\"][x] = geocode_result[0][\"geometry\"][\"location\"][\"lat\"]\n",
      "<ipython-input-14-3e04e6a4b050>:7: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  arrests[\"longitude\"][x] = geocode_result[0][\"geometry\"][\"location\"][\"lng\"]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The address was wrong...\n",
      "The address was wrong...\n",
      "The address was wrong...\n",
      "The address was wrong...\n"
     ]
    }
   ],
   "source": [
    "#for loop using geocoding to get longitude and latitude coordinates for each address\n",
    "for i in range(3000, 4000, 100):\n",
    "    for x in range(i, i+100):\n",
    "        try:\n",
    "            time.sleep(1)\n",
    "            geocode_result = gmaps.geocode(arrests[\"placeofarrest\"][x])\n",
    "            arrests[\"latitude\"][x] = geocode_result[0][\"geometry\"][\"location\"][\"lat\"]\n",
    "            arrests[\"longitude\"][x] = geocode_result[0][\"geometry\"][\"location\"][\"lng\"]\n",
    "        except IndexError:\n",
    "            print(\"The address was wrong...\")\n",
    "        except Exception as e:\n",
    "            print(\"unexpected error occured.\", e)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.5 ('geo')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "8024ccf16af522f08843a35ed1a25823c82e37522445718ef9e6c3ac7fb4d2d8"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
